github:
  api_url: https://api.github.com

tracking:
  since: "2025-07-01"

  users:
    - oliver-butterley
    - truonghoangle
    - MarkusFerdinandDablander
    - a-dangelo
    - Zhang-Liao
    - mpenciak
    - astefano
    - faenuccio
    - ChristianoBraga
    - jinxinglim
    - mkovaxx

  exclude:
    - repo: leanprover-community/mathlib4
      user: faenuccio
    - repo: leanprover-community/mathlib4
      user: a-dangelo
    - repo: leanprover-community/mathlib4
      user: mpenciak
    - repo: leanprover-community/mathlib4
      numbers: [26807, 26810, 26840, 26842, 26848, 26851, 26852, 26853, 26923, 27008]

  repos:
    - owner: AeneasVerif
      name: aeneas
    - owner: AeneasVerif
      name: charon
    - owner: leanprover
      name: cslib
    - owner: verus-lang
      name: verus
    - owner: leanprover-community
      name: mathlib4
      bors: true
